# Site settings
name: Ichi
description: "Jekyll Theme"

# Unsplash
unsplash_client_id:

# Social
facebook_username: test
twitter_username: test
google_plus_username: test
dribbble_username: test

plugins:
  - "jekyll-github-metadata"